### ISSUE TITLE
PR Roadmap

### ISSUE THREAD

**Issue by jeremylt** [jeremylt/LFAToolkit.jl#53]
The roadmap for this collection of PRs is unclear to me. Many of the commits seem to be intermingled across multiple PRs. This issue is my effort to try to come up with a plan to get all this work merged.

---

Here is my understanding of the features we want to add:

- Transplanted quadtrature (Mostly in #48, but that has some extra content)
  - Sausage transformation
  - Kosloff and Tal-Ezer transformation
  -  Hale and Trefethen Strip transformation
- Advection example (#51)
  - New convenience constructor
  - New example `ex010_advection.jl` and `demo010_advection.ipynb`
  - Documentation update in `docs/src/examples/advection.md`
- Advection example with SUPG (#52)
  - New convenience constructor
  - New example `ex011_advection_supg.jl` and `demo011_advection_supg.ipynb`
  - Documentation update in `docs/src/examples/advection.md`

I think that once we get these three PRs fixed up and merged, then we can move to the other two.

The commit history on these branches is messy - I'm fine with squash-merge if we can get the contents of those branches rebased for the updates in main and the have the formatting and documentation issues all tidied up, though the best case scenario would be 'clean' branches with one or two relevant commits to add each new feature.

---

This is a general checklist for every PR:
- Formatting
  - run `julia .Style.jl` to automatically fix all formatting
- Documentation
  - Docstrings - every function added should have a docstring with the fields `Arguments`, `Returns` and `Example`
  - Doctest - every function added should have at least one doctest covering all relevant use cases
  - Markdown - new functions need to be added to `docs/src` in the relevant `*.md` file

<details><summary>Example docstring + doctest</summary>

~~~julia
"""
```julia
gausslobattoquadrature(q, weights)
```

Construct a Gauss-Legendre-Lobatto quadrature

# Arguments:
- `q`:        number of Gauss-Legendre-Lobatto points
- `weights`:  boolean flag indicating if quadrature weights are desired

# Returns:
- Gauss-Legendre-Lobatto quadrature points or points and weights

# Example:
```jldoctest
# generate Gauss-Legendre-Lobatto points
quadraturepoints = LFAToolkit.gausslobattoquadrature(5, false);

# verify
truepoints = [-1.0, -√(3/7), 0.0, √(3/7), 1.0];
@assert truepoints ≈ quadraturepoints

# generate Gauss-Legendre-Lobatto points and weights
quadraturepoints, quadratureweights = LFAToolkit.gausslobattoquadrature(5, true);

# verify
trueweights = [1/10, 49/90, 32/45, 49/90, 1/10];
@assert trueweights ≈ quadratureweights

# output

```
"""
~~~

</details>

---

Did I capture the main plan? Am I missing anything?

**Comment by AdelekeBankole** [comment]
Thanks Jeremy for this. I think I will be able to get back to this from Friday morning. I would like to clean up all the messy commits. Maybe we can have a call together on Friday?

**Comment by AdelekeBankole** [comment]
I think I addressed the issues, should I push for you to see before trying squash-merge and rebasing. @jeremylt pls what do you mean by new convenience constructor?
