### ISSUE TITLE
[discussion] advection diffusion operator

### ISSUE THREAD

**Issue by yslan** [jeremylt/LFAToolkit.jl#61]
Hi there,

I am trying to build an advection diffusion operator and I want to apply Jacobi PC as a starter.
I try to follow the code `GalleryOperator("advection",...`, `GalleryOperator("diffusion",...` and the example demo301: linear elasticity

The weak form requires three input argument 
```
    function advdiffusionweakform(u::Array{Float64}, du::Array{Float64}, w::Array{Float64})
        dv = parameters.wind * u * w[1] + du * w[1]
        return [dv]
    end

    inputs = [
        OperatorField(basis, [EvaluationMode.interpolation], "adv"), 
        OperatorField(basis, [EvaluationMode.gradient], "gradent of deformation"),
        OperatorField(basis, [EvaluationMode.quadratureweights], "quadrature weights"),
    ]
```
which will build the elementmatrix of size (p+1) x 2(p+1) since `getelementmatrix` goes through all inputs but not allowing using two evaluation modes at the same time.

Since it's a linear operations, is there any way to combine two operator so advection + diffusion = advdiffusion?
Or do I have to go through `Base.getproperty` and modify the interface to fit my weakform function?

Thanks,
Yu-Hsiang

**Comment by jeremylt** [comment]
This says there are two separate inputs, each with one evaluation mode
```
    inputs = [
        OperatorField(basis, [EvaluationMode.interpolation], "adv"), 
        OperatorField(basis, [EvaluationMode.gradient], "gradent of deformation"),
        OperatorField(basis, [EvaluationMode.quadratureweights], "quadrature weights"),
    ]
 ```
 
 I think you need
 ```
     inputs = [
        OperatorField(basis, [EvaluationMode.interpolation, EvaluationMode.gradient], "adv and gradent of deformation"),
        OperatorField(basis, [EvaluationMode.quadratureweights], "quadrature weights"),
    ]
```

That will combine the first two inputs in the weak form. Something like this, I think
```
    function advdiffusionweakform(udu::Array{Float64}, w::Array{Float64})
        u = udu[1]
        du = udu[2:end]
        dv = parameters.wind * u * w[1] + du * w[1]
        return [dv]
    end
```

**Comment by yslan** [comment]
Thanks, that works!

I also found a similar example in the advection_supg, which uses Matrix{Float64} in the weakform function. Somehow that only works for 1D problem.
